language: csharp
solution: BrainfuckCompilerInterpreter.sln
install:
  - nuget restore BrainfuckCompilerInterpreter.sln
  - nuget install NUnit.Runners -Version 3.10.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BrainfuckCompilerInterpreter.sln
  - mono ./testrunner/NUnit.Runners.3.10.1/tools/nunit-console.exe ./Tests/bin/Release/Tests.dll
