language: csharp
solution: BrainfuckCompilerInterpreter.sln
install:
  - nuget restore BrainfuckCompilerInterpreter.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BrainfuckCompilerInterpreter.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll
